export default {
    GET_VACATIONS: "GET_VACATION_ACTION",
    GET_VACATIONS_SUCCESS: "GET_COUNTRIES_SUCCESS",
    GET_VACATIONS_PENDING: "GET_COUNTRIES_PENDING",
    SAVE_VACATION: "SAVE_VACATION_ACTION",
    SAVE_USER: "SAVE_USER_ACTION",
    GET_VACATION_SUCCESS: "GET_VACATION_SUCCESS",
    ADD_TO_FAVORITS: " ADD_TO_FAVORITS",
    SET_VACATIONS: " SET_VACATIONS"

};
