export default {
    GET_VACATIONS: "GET_VACATION_ACTION",
    GET_VACATIONS_SUCCESS: "GET_COUNTRIES_SUCCESS",
    GET_VACATIONS_PENDING: "GET_COUNTRIES_PENDING",
    GET_VACATION_SUCCESS: "GET_VACATION_SUCCESS",
    SET_VACATIONS: " SET_VACATIONS",
    SET_USER: " SET_USER",

};
